---
- name: This sets up an httpd webserver
  hosts: web
  vars:
    name: "--rajesh kumar in playbook--"
    message: "Hello everyone"
    package: httpd

  tasks:
  - name: Install the git - ntp - vim apps
    yum: name={{ item }} state=present
    with_items:
      - git
      - ntp
      - vim
    when: ansible_os_family == "RedHat"
  - name: Install the apache2 apps
    apt: name={{ package }} state=present
    when: ansible_os_family == "Debian"
  - name: start the httpd service
    service: name={{ package }} state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
  - debug:
      msg: My Name is {{ name }}  and my message is {{ message }}
...	

