---
- name: to create folder Abril in Windows
  hosts: all
  tasks:
  - name: create folder
    win_file:
      path: C:/asz/AbrilPlaybook/
      state: directory

  - name: Create file
    win_lineinfile:
      path: C:/asz/AbrilPlaybook/readme2.txt
      line: "Hello world"
      create: yes
...
