---
- name: Windows test
  hosts: windows

  tasks:
  - name: Create a file
    win_file: path="C:\\asz\\Hugo\\helloworld.ps1" state=touch
  - name: Add content to file
    win_lineinfile: path="C:\\asz\\Hugo\\helloworld.ps1" state=present line="mkdir devopsschool"
  - name: Run script
    win_shell: C:\asz\Hugo\helloworld.ps1
...

