---
- hosts: apache
  become: True

  tasks:
   - name: install apache
     package:
      name: httpd
      state: present

   - name: configuration file update
     template: 
       src: files/httpd.j2
       dest: /etc/httpd/conf/httpd.conf 

   - name: copy index
     copy:
      src: index.html
      dest: /var/www/html

   - name: Restart service httpd, in all cases
     service:
      name: httpd
      state: restarted
