---
- name: This sets up an httpd webserver
  hosts: all
  vars:
    name: "rod"
    message: "Hello everyone"
    package: httpd
  vars_files:
    - vars.yaml
  vars_prompt:
    - name: "Version"
      prompt: "Which version Do you want to install?"

  tasks:
  - name: include default step variables
    include_vars: vars-tasks.yaml
  - name: Install the httpd apps
    yum: name={{ package }} state=present
  - name: start the httpd service
    service: name={{ package }} state=started
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
  - debug:
      msg: My Name is {{ name }}  and my message is {{ message }}
  - debug:
      msg: Prompt message is {{ Version }}

...
