---
- name: This sets up an httpd webserver
  hosts: web

  tasks:
  - name: include_var_file
    include_vars:
      var_file.yml
  - name: Install httpd apps
    yum:
      name: "{{var_file}}"
      state: present
...
