---
- name: to create folder Janeth in Windows
  hosts: all
  tasks:
  - name: create folder
    win_file:
      path: C:/HPE/janeth/
      state: directory

  - name: Create file
    win_lineinfile:
      path: C:/HPE/janeth/readme.txt
      line: "I love India by Janeth"
      create: yes
...
