--- 
- name: Day5               
  hosts: localhost 
  connection: local 
  gather_facts: False       
  tasks:          
  - name: touch without state
    touch:       
      file: ./Janeth.txt
    register: touch_out 
  - debug:         
      var: touch_out         
  - name: touchw with state (after create)       
    touch:        
       file: ./Janeth.txt       
       state: present          
  - name: touch with absent 
    touch:      
       file: ./Janeth.txt   
       state: absent        
  - name: touch absent with no file         
    touch:   
      file: ./Janeth.txt                
      state: absent                                  
...
