---
- name:  Install httpd
  hosts: web
  vars:
     service: httpd
  tasks:
    - name: Install {{ service }}
      yum:
          name: "{{ service }}"
          state: installed
    - name: Find txt on /etc
      shell:  find /usr/share -name *.txt
      register: find_out
      ignore_errors: True
...
