---
- name: This sets up an httpd webserver
  hosts: localhost
  vars_files:
    - "vars_selene.yaml"

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present 
  - debug:
      msg: My Name is {{ myname }} 
  - debug:      
      msg: My Age is {{ age }}
  - debug:
      msg: My port is {{ port }}
