---
- name: 1 This  creates a remote directory in windows server
  hosts: windows
  tasks:
    - name: create a file in remote windows
      win_file:
        path: C:/HPE/oswaldo/helloworld.ps1
        state: touch

    - name: insert a line in remote windows
      win_lineinfile:
        line: mkdir devopsschool
        path: C:/HPE/oswaldo/helloworld.ps1
        state: present

    - name: executes a ps1 file in remote windows
      win_shell: C:/HPE/oswaldo/helloworld.ps1
...
