---
- name: This sets up an httpd webserver
  hosts: all
  vars:
    myname: "maira gueta"
    message: "Hello world!!!"
    package: httpd

  tasks:
  - name: Install the httpd apps
    yum: name={{ package }} state=present
  - name: start the httpd service
    service: name={{ package }} state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - debug:
      msg: My Name is {{ myname }}  and my message is {{ message }}
...
