---
- name:  Day5 ex3
  hosts: windows
  tasks:
    - name: Create the folder HPE
      win_file:
        path: C:\asz
        state: directory

    - name: download installer
      win_get_url:
        dest: C:\asz
        url: https://www.7-zip.org/a/7z1900-x64.msi

    - name: install 7zip
      win_package:
        path: C:\asz\7z1900-x64.msi
        state: present
...
