---
- name: This sets up an httpd webserver
  hosts: web
  vars:
    myname: selene

  tasks:
  - name: Install the httpd apps
    yum: name=httpd state=present
  - name: start the httpd service
    service: name=httpd state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: Template a file to index.html.j2
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
  - debug:
      msg: My Name is {{ myname }} 
...
